apiVersion: aiops.com/v1
kind: LogPilot
metadata:
  labels:
    app.kubernetes.io/name: logpilot
    app.kubernetes.io/managed-by: kustomize
  name: logpilot-sample
spec:
  lokiURL: "http://172.17.99.87:3100"
  lokiPromQL: '{app="payment"} |= `ERROR`'
  llmEndpoint: "http://192.168.1.111:11434/v1"
  llmToken: "ollama"
  llmModel: "qwen2.5"
  feishuWebhook: "https://open.feishu.cn/open-apis/bot/v2/hook/d219b128-1520-40b3-b7ce-8df8c01422d2"

