# permissions for end users to edit logpilots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: logpilot
    app.kubernetes.io/managed-by: kustomize
  name: logpilot-editor-role
rules:
- apiGroups:
  - aiops.com
  resources:
  - logpilots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.com
  resources:
  - logpilots/status
  verbs:
  - get
